QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets core

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    src/callback.cpp \
    src/http_client.cpp \
    src/httpclient.cpp \
    src/imagewidget.cpp \
    main.cpp \
    src/lib/crash/crashhandler.cpp \
    src/lib/crash/crashinfo.cpp \
    src/lib/developermode.cpp \
    src/lib/log.cpp \
    src/lib/log/datetime.cpp \
    src/lib/log/logmessage.cpp \
    src/mainwindow.cpp \
    src/network.c \
    src/test.cpp \

HEADERS += \
    include/callback.h \
    include/lib/cache.h \
    include/lib/cache/jsoncache.h \
    include/lib/crash/crashhandler.h \
    include/lib/crash/crashinfo.h \
    include/lib/crashhandler.h \
    include/lib/developermode.h \
    include/http_client.h \
    include/http_client.h \
    include/imagewidget.h \
    include/lib/format.h \
    include/lib/json.h \
    include/lib/log.h \
    include/lib/log/datetime.h \
    include/lib/log/logmessage.h \
    include/lib/log/logtype.h \
    include/lib/paths.h \
    include/mainwindow.h \
    include/network.h \
    thirdparty/json/include/nlohmann/adl_serializer.hpp \
    thirdparty/json/include/nlohmann/byte_container_with_subtype.hpp \
    thirdparty/json/include/nlohmann/detail/conversions/from_json.hpp \
    thirdparty/json/include/nlohmann/detail/conversions/to_chars.hpp \
    thirdparty/json/include/nlohmann/detail/conversions/to_json.hpp \
    thirdparty/json/include/nlohmann/detail/exceptions.hpp \
    thirdparty/json/include/nlohmann/detail/hash.hpp \
    thirdparty/json/include/nlohmann/detail/input/binary_reader.hpp \
    thirdparty/json/include/nlohmann/detail/input/input_adapters.hpp \
    thirdparty/json/include/nlohmann/detail/input/json_sax.hpp \
    thirdparty/json/include/nlohmann/detail/input/lexer.hpp \
    thirdparty/json/include/nlohmann/detail/input/parser.hpp \
    thirdparty/json/include/nlohmann/detail/input/position_t.hpp \
    thirdparty/json/include/nlohmann/detail/iterators/internal_iterator.hpp \
    thirdparty/json/include/nlohmann/detail/iterators/iter_impl.hpp \
    thirdparty/json/include/nlohmann/detail/iterators/iteration_proxy.hpp \
    thirdparty/json/include/nlohmann/detail/iterators/iterator_traits.hpp \
    thirdparty/json/include/nlohmann/detail/iterators/json_reverse_iterator.hpp \
    thirdparty/json/include/nlohmann/detail/iterators/primitive_iterator.hpp \
    thirdparty/json/include/nlohmann/detail/json_pointer.hpp \
    thirdparty/json/include/nlohmann/detail/json_ref.hpp \
    thirdparty/json/include/nlohmann/detail/macro_scope.hpp \
    thirdparty/json/include/nlohmann/detail/macro_unscope.hpp \
    thirdparty/json/include/nlohmann/detail/meta/call_std/begin.hpp \
    thirdparty/json/include/nlohmann/detail/meta/call_std/end.hpp \
    thirdparty/json/include/nlohmann/detail/meta/cpp_future.hpp \
    thirdparty/json/include/nlohmann/detail/meta/detected.hpp \
    thirdparty/json/include/nlohmann/detail/meta/identity_tag.hpp \
    thirdparty/json/include/nlohmann/detail/meta/is_sax.hpp \
    thirdparty/json/include/nlohmann/detail/meta/type_traits.hpp \
    thirdparty/json/include/nlohmann/detail/meta/void_t.hpp \
    thirdparty/json/include/nlohmann/detail/output/binary_writer.hpp \
    thirdparty/json/include/nlohmann/detail/output/output_adapters.hpp \
    thirdparty/json/include/nlohmann/detail/output/serializer.hpp \
    thirdparty/json/include/nlohmann/detail/string_escape.hpp \
    thirdparty/json/include/nlohmann/detail/value_t.hpp \
    thirdparty/json/include/nlohmann/json.hpp \
    thirdparty/json/include/nlohmann/json_fwd.hpp \
    thirdparty/json/include/nlohmann/ordered_map.hpp \
    thirdparty/json/include/nlohmann/thirdparty/hedley/hedley.hpp \
    thirdparty/json/include/nlohmann/thirdparty/hedley/hedley_undef.hpp \
    thirdparty/json/single_include/nlohmann/json.hpp \

FORMS += \
    mainwindow.ui

TRANSLATIONS += \
    DAC_en_US.ts
CONFIG += lrelease
CONFIG += embed_translations

VERSION = 1.2.3.4

DEFINES += APP_VERSION=\\\"$$VERSION\\\"


# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    thirdparty/json/CITATION.cff \
    thirdparty/json/CMakeLists.txt \
    thirdparty/json/CODE_OF_CONDUCT.md \
    thirdparty/json/ChangeLog.md \
    thirdparty/json/LICENSE.MIT \
    thirdparty/json/README.md \
    thirdparty/json/appveyor.yml \
    thirdparty/json/benchmarks/CMakeLists.txt \
    thirdparty/json/cmake/ci.cmake \
    thirdparty/json/cmake/config.cmake.in \
    thirdparty/json/cmake/download_test_data.cmake \
    thirdparty/json/cmake/nlohmann_jsonConfigVersion.cmake.in \
    thirdparty/json/cmake/pkg-config.pc.in \
    thirdparty/json/doc/README.md \
    thirdparty/json/doc/avatars.png \
    thirdparty/json/doc/docset/Info.plist \
    thirdparty/json/doc/docset/README.md \
    thirdparty/json/doc/docset/docSet.sql \
    thirdparty/json/doc/docset/docset.json \
    thirdparty/json/doc/docset/icon.png \
    thirdparty/json/doc/docset/icon@2x.png \
    thirdparty/json/doc/examples/README.output \
    thirdparty/json/doc/examples/accept__string.output \
    thirdparty/json/doc/examples/array.output \
    thirdparty/json/doc/examples/array_t.output \
    thirdparty/json/doc/examples/at__object_t_key_type.output \
    thirdparty/json/doc/examples/at__object_t_key_type_const.output \
    thirdparty/json/doc/examples/at__size_type.output \
    thirdparty/json/doc/examples/at__size_type_const.output \
    thirdparty/json/doc/examples/at_json_pointer.output \
    thirdparty/json/doc/examples/at_json_pointer_const.output \
    thirdparty/json/doc/examples/back.output \
    thirdparty/json/doc/examples/basic_json__CompatibleType.output \
    thirdparty/json/doc/examples/basic_json__InputIt_InputIt.output \
    thirdparty/json/doc/examples/basic_json__basic_json.output \
    thirdparty/json/doc/examples/basic_json__copyassignment.output \
    thirdparty/json/doc/examples/basic_json__list_init_t.output \
    thirdparty/json/doc/examples/basic_json__moveconstructor.output \
    thirdparty/json/doc/examples/basic_json__nullptr_t.output \
    thirdparty/json/doc/examples/basic_json__size_type_basic_json.output \
    thirdparty/json/doc/examples/basic_json__value.output \
    thirdparty/json/doc/examples/basic_json__value_ptr.output \
    thirdparty/json/doc/examples/basic_json__value_t.output \
    thirdparty/json/doc/examples/begin.output \
    thirdparty/json/doc/examples/binary.output \
    thirdparty/json/doc/examples/binary_t.output \
    thirdparty/json/doc/examples/boolean_t.output \
    thirdparty/json/doc/examples/cbegin.output \
    thirdparty/json/doc/examples/cend.output \
    thirdparty/json/doc/examples/clear.output \
    thirdparty/json/doc/examples/contains.output \
    thirdparty/json/doc/examples/contains_json_pointer.output \
    thirdparty/json/doc/examples/count.output \
    thirdparty/json/doc/examples/crbegin.output \
    thirdparty/json/doc/examples/crend.output \
    thirdparty/json/doc/examples/diagnostics_extended.output \
    thirdparty/json/doc/examples/diagnostics_standard.output \
    thirdparty/json/doc/examples/diff.output \
    thirdparty/json/doc/examples/dump.output \
    thirdparty/json/doc/examples/emplace.output \
    thirdparty/json/doc/examples/emplace_back.output \
    thirdparty/json/doc/examples/empty.output \
    thirdparty/json/doc/examples/end.output \
    thirdparty/json/doc/examples/erase__IteratorType.output \
    thirdparty/json/doc/examples/erase__IteratorType_IteratorType.output \
    thirdparty/json/doc/examples/erase__key_type.output \
    thirdparty/json/doc/examples/erase__size_type.output \
    thirdparty/json/doc/examples/exception.output \
    thirdparty/json/doc/examples/find__key_type.output \
    thirdparty/json/doc/examples/flatten.output \
    thirdparty/json/doc/examples/from_bson.output \
    thirdparty/json/doc/examples/from_cbor.output \
    thirdparty/json/doc/examples/from_msgpack.output \
    thirdparty/json/doc/examples/from_ubjson.output \
    thirdparty/json/doc/examples/front.output \
    thirdparty/json/doc/examples/get__PointerType.output \
    thirdparty/json/doc/examples/get__ValueType_const.output \
    thirdparty/json/doc/examples/get_binary.output \
    thirdparty/json/doc/examples/get_ptr.output \
    thirdparty/json/doc/examples/get_ref.output \
    thirdparty/json/doc/examples/get_to.output \
    thirdparty/json/doc/examples/insert.output \
    thirdparty/json/doc/examples/insert__count.output \
    thirdparty/json/doc/examples/insert__ilist.output \
    thirdparty/json/doc/examples/insert__range.output \
    thirdparty/json/doc/examples/insert__range_object.output \
    thirdparty/json/doc/examples/invalid_iterator.output \
    thirdparty/json/doc/examples/is_array.output \
    thirdparty/json/doc/examples/is_binary.output \
    thirdparty/json/doc/examples/is_boolean.output \
    thirdparty/json/doc/examples/is_discarded.output \
    thirdparty/json/doc/examples/is_null.output \
    thirdparty/json/doc/examples/is_number.output \
    thirdparty/json/doc/examples/is_number_float.output \
    thirdparty/json/doc/examples/is_number_integer.output \
    thirdparty/json/doc/examples/is_number_unsigned.output \
    thirdparty/json/doc/examples/is_object.output \
    thirdparty/json/doc/examples/is_primitive.output \
    thirdparty/json/doc/examples/is_string.output \
    thirdparty/json/doc/examples/is_structured.output \
    thirdparty/json/doc/examples/items.output \
    thirdparty/json/doc/examples/iterator_wrapper.output \
    thirdparty/json/doc/examples/json_lines.output \
    thirdparty/json/doc/examples/json_pointer.output \
    thirdparty/json/doc/examples/json_pointer__back.output \
    thirdparty/json/doc/examples/json_pointer__empty.output \
    thirdparty/json/doc/examples/json_pointer__operator_add.output \
    thirdparty/json/doc/examples/json_pointer__operator_add_binary.output \
    thirdparty/json/doc/examples/json_pointer__parent_pointer.output \
    thirdparty/json/doc/examples/json_pointer__pop_back.output \
    thirdparty/json/doc/examples/json_pointer__push_back.output \
    thirdparty/json/doc/examples/json_pointer__to_string.output \
    thirdparty/json/doc/examples/max_size.output \
    thirdparty/json/doc/examples/merge_patch.output \
    thirdparty/json/doc/examples/meta.output \
    thirdparty/json/doc/examples/number_float_t.output \
    thirdparty/json/doc/examples/number_integer_t.output \
    thirdparty/json/doc/examples/number_unsigned_t.output \
    thirdparty/json/doc/examples/object.output \
    thirdparty/json/doc/examples/object_t.output \
    thirdparty/json/doc/examples/operator__ValueType.output \
    thirdparty/json/doc/examples/operator__equal.output \
    thirdparty/json/doc/examples/operator__equal__nullptr_t.output \
    thirdparty/json/doc/examples/operator__greater.output \
    thirdparty/json/doc/examples/operator__greaterequal.output \
    thirdparty/json/doc/examples/operator__less.output \
    thirdparty/json/doc/examples/operator__lessequal.output \
    thirdparty/json/doc/examples/operator__notequal.output \
    thirdparty/json/doc/examples/operator__notequal__nullptr_t.output \
    thirdparty/json/doc/examples/operator__value_t.output \
    thirdparty/json/doc/examples/operator_deserialize.output \
    thirdparty/json/doc/examples/operator_literal_json.output \
    thirdparty/json/doc/examples/operator_literal_json_pointer.output \
    thirdparty/json/doc/examples/operator_serialize.output \
    thirdparty/json/doc/examples/operatorarray__key_type.output \
    thirdparty/json/doc/examples/operatorarray__key_type_const.output \
    thirdparty/json/doc/examples/operatorarray__size_type.output \
    thirdparty/json/doc/examples/operatorarray__size_type_const.output \
    thirdparty/json/doc/examples/operatorjson_pointer.output \
    thirdparty/json/doc/examples/operatorjson_pointer_const.output \
    thirdparty/json/doc/examples/ordered_map.output \
    thirdparty/json/doc/examples/other_error.output \
    thirdparty/json/doc/examples/out_of_range.output \
    thirdparty/json/doc/examples/parse__allow_exceptions.output \
    thirdparty/json/doc/examples/parse__array__parser_callback_t.output \
    thirdparty/json/doc/examples/parse__contiguouscontainer__parser_callback_t.output \
    thirdparty/json/doc/examples/parse__istream__parser_callback_t.output \
    thirdparty/json/doc/examples/parse__iterator_pair.link \
    thirdparty/json/doc/examples/parse__iterator_pair.output \
    thirdparty/json/doc/examples/parse__pointers.link \
    thirdparty/json/doc/examples/parse__pointers.output \
    thirdparty/json/doc/examples/parse__string__parser_callback_t.output \
    thirdparty/json/doc/examples/parse_error.output \
    thirdparty/json/doc/examples/patch.output \
    thirdparty/json/doc/examples/push_back.output \
    thirdparty/json/doc/examples/push_back__initializer_list.output \
    thirdparty/json/doc/examples/push_back__object_t__value.output \
    thirdparty/json/doc/examples/rbegin.output \
    thirdparty/json/doc/examples/rend.output \
    thirdparty/json/doc/examples/sax_parse.output \
    thirdparty/json/doc/examples/size.output \
    thirdparty/json/doc/examples/std_hash.output \
    thirdparty/json/doc/examples/std_swap.output \
    thirdparty/json/doc/examples/string_t.output \
    thirdparty/json/doc/examples/swap__array_t.output \
    thirdparty/json/doc/examples/swap__binary_t.output \
    thirdparty/json/doc/examples/swap__object_t.output \
    thirdparty/json/doc/examples/swap__reference.output \
    thirdparty/json/doc/examples/swap__string_t.output \
    thirdparty/json/doc/examples/to_bson.output \
    thirdparty/json/doc/examples/to_cbor.output \
    thirdparty/json/doc/examples/to_msgpack.output \
    thirdparty/json/doc/examples/to_string.output \
    thirdparty/json/doc/examples/to_ubjson.output \
    thirdparty/json/doc/examples/type.output \
    thirdparty/json/doc/examples/type_error.output \
    thirdparty/json/doc/examples/type_name.output \
    thirdparty/json/doc/examples/unflatten.output \
    thirdparty/json/doc/examples/update.output \
    thirdparty/json/doc/examples/update__range.output \
    thirdparty/json/doc/index.md \
    thirdparty/json/doc/json.gif \
    thirdparty/json/doc/mkdocs/docs/api/adl_serializer/from_json.md \
    thirdparty/json/doc/mkdocs/docs/api/adl_serializer/index.md \
    thirdparty/json/doc/mkdocs/docs/api/adl_serializer/to_json.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/accept.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/array.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/array_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/at.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/back.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/basic_json.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/begin.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/binary.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/binary_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/boolean_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/cbegin.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/cbor_tag_handler_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/cend.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/clear.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/contains.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/count.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/crbegin.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/crend.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/diff.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/dump.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/emplace.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/emplace_back.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/empty.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/end.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/erase.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/error_handler_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/exception.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/find.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/flatten.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/from_bson.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/from_cbor.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/from_msgpack.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/from_ubjson.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/front.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/get.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/get_allocator.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/get_binary.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/get_ptr.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/get_ref.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/get_to.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/index.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/input_format_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/insert.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/invalid_iterator.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_array.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_binary.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_boolean.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_discarded.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_null.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_number.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_number_float.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_number_integer.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_number_unsigned.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_object.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_primitive.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_string.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/is_structured.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/items.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/json_serializer.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/max_size.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/merge_patch.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/meta.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/number_float_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/number_integer_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/number_unsigned_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/object.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/object_comparator_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/object_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator+=.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator=.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator[].md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_ValueType.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_eq.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_ge.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_gt.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_gtgt.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_le.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_literal_json.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_literal_json_pointer.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_lt.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_ltlt.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_ne.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/operator_value_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/other_error.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/out_of_range.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/parse.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/parse_error.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/parse_event_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/parser_callback_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/patch.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/push_back.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/rbegin.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/rend.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/sax_parse.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/size.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/std_hash.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/std_swap.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/string_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/swap.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/to_bson.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/to_cbor.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/to_msgpack.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/to_string.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/to_ubjson.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/type.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/type_error.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/type_name.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/unflatten.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/update.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/value.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/value_t.md \
    thirdparty/json/doc/mkdocs/docs/api/basic_json/~basic_json.md \
    thirdparty/json/doc/mkdocs/docs/api/byte_container_with_subtype/byte_container_with_subtype.md \
    thirdparty/json/doc/mkdocs/docs/api/byte_container_with_subtype/clear_subtype.md \
    thirdparty/json/doc/mkdocs/docs/api/byte_container_with_subtype/has_subtype.md \
    thirdparty/json/doc/mkdocs/docs/api/byte_container_with_subtype/index.md \
    thirdparty/json/doc/mkdocs/docs/api/byte_container_with_subtype/set_subtype.md \
    thirdparty/json/doc/mkdocs/docs/api/byte_container_with_subtype/subtype.md \
    thirdparty/json/doc/mkdocs/docs/api/json.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/back.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/empty.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/index.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/json_pointer.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/operator_slash.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/operator_slasheq.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/operator_string.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/parent_pointer.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/pop_back.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/push_back.md \
    thirdparty/json/doc/mkdocs/docs/api/json_pointer/to_string.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/binary.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/boolean.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/end_array.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/end_object.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/index.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/key.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/null.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/number_float.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/number_integer.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/number_unsigned.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/parse_error.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/start_array.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/start_object.md \
    thirdparty/json/doc/mkdocs/docs/api/json_sax/string.md \
    thirdparty/json/doc/mkdocs/docs/api/macros/index.md \
    thirdparty/json/doc/mkdocs/docs/api/macros/json_assert.md \
    thirdparty/json/doc/mkdocs/docs/api/ordered_json.md \
    thirdparty/json/doc/mkdocs/docs/api/ordered_map.md \
    thirdparty/json/doc/mkdocs/docs/features/arbitrary_types.md \
    thirdparty/json/doc/mkdocs/docs/features/binary_formats/bson.md \
    thirdparty/json/doc/mkdocs/docs/features/binary_formats/cbor.md \
    thirdparty/json/doc/mkdocs/docs/features/binary_formats/index.md \
    thirdparty/json/doc/mkdocs/docs/features/binary_formats/messagepack.md \
    thirdparty/json/doc/mkdocs/docs/features/binary_formats/ubjson.md \
    thirdparty/json/doc/mkdocs/docs/features/binary_values.md \
    thirdparty/json/doc/mkdocs/docs/features/comments.md \
    thirdparty/json/doc/mkdocs/docs/features/element_access/checked_access.md \
    thirdparty/json/doc/mkdocs/docs/features/element_access/default_value.md \
    thirdparty/json/doc/mkdocs/docs/features/element_access/index.md \
    thirdparty/json/doc/mkdocs/docs/features/element_access/unchecked_access.md \
    thirdparty/json/doc/mkdocs/docs/features/enum_conversion.md \
    thirdparty/json/doc/mkdocs/docs/features/iterators.md \
    thirdparty/json/doc/mkdocs/docs/features/json_patch.md \
    thirdparty/json/doc/mkdocs/docs/features/json_pointer.md \
    thirdparty/json/doc/mkdocs/docs/features/macros.md \
    thirdparty/json/doc/mkdocs/docs/features/merge_patch.md \
    thirdparty/json/doc/mkdocs/docs/features/object_order.md \
    thirdparty/json/doc/mkdocs/docs/features/parsing/index.md \
    thirdparty/json/doc/mkdocs/docs/features/parsing/json_lines.md \
    thirdparty/json/doc/mkdocs/docs/features/parsing/parse_exceptions.md \
    thirdparty/json/doc/mkdocs/docs/features/parsing/parser_callbacks.md \
    thirdparty/json/doc/mkdocs/docs/features/parsing/sax_interface.md \
    thirdparty/json/doc/mkdocs/docs/features/types/index.md \
    thirdparty/json/doc/mkdocs/docs/features/types/number_handling.md \
    thirdparty/json/doc/mkdocs/docs/home/code_of_conduct.md \
    thirdparty/json/doc/mkdocs/docs/home/design_goals.md \
    thirdparty/json/doc/mkdocs/docs/home/exceptions.md \
    thirdparty/json/doc/mkdocs/docs/home/faq.md \
    thirdparty/json/doc/mkdocs/docs/home/license.md \
    thirdparty/json/doc/mkdocs/docs/home/releases.md \
    thirdparty/json/doc/mkdocs/docs/home/sponsors.md \
    thirdparty/json/doc/mkdocs/docs/images/callback_events.png \
    thirdparty/json/doc/mkdocs/docs/images/json_syntax_number.png \
    thirdparty/json/doc/mkdocs/docs/images/range-begin-end.svg \
    thirdparty/json/doc/mkdocs/docs/images/range-rbegin-rend.svg \
    thirdparty/json/doc/mkdocs/docs/index.md \
    thirdparty/json/doc/mkdocs/docs/integration/cmake.md \
    thirdparty/json/doc/mkdocs/docs/integration/conan/CMakeLists.txt \
    thirdparty/json/doc/mkdocs/docs/integration/conan/Conanfile.txt \
    thirdparty/json/doc/mkdocs/docs/integration/index.md \
    thirdparty/json/doc/mkdocs/docs/integration/package_managers.md \
    thirdparty/json/doc/mkdocs/docs/integration/pkg-config.md \
    thirdparty/json/doc/mkdocs/docs/integration/vcpkg/CMakeLists.txt \
    thirdparty/json/doc/mkdocs/mkdocs.yml \
    thirdparty/json/doc/mkdocs/requirements.txt \
    thirdparty/json/doc/mkdocs/scripts/check_structure.py \
    thirdparty/json/doc/usages/ios.png \
    thirdparty/json/doc/usages/macos.png \
    thirdparty/json/meson.build \
    thirdparty/json/nlohmann_json.natvis \
    thirdparty/json/test/CMakeLists.txt \
    thirdparty/json/test/cmake_add_subdirectory/CMakeLists.txt \
    thirdparty/json/test/cmake_add_subdirectory/project/CMakeLists.txt \
    thirdparty/json/test/cmake_fetch_content/CMakeLists.txt \
    thirdparty/json/test/cmake_fetch_content/project/CMakeLists.txt \
    thirdparty/json/test/cmake_import/CMakeLists.txt \
    thirdparty/json/test/cmake_import/project/CMakeLists.txt \
    thirdparty/json/test/cmake_import_minver/CMakeLists.txt \
    thirdparty/json/test/cmake_import_minver/project/CMakeLists.txt \
    thirdparty/json/test/cmake_target_include_directories/CMakeLists.txt \
    thirdparty/json/test/cmake_target_include_directories/project/CMakeLists.txt \
    thirdparty/json/test/cuda_example/CMakeLists.txt \
    thirdparty/json/test/cuda_example/json_cuda.cu \
    thirdparty/json/test/reports/2016-08-29-fuzz/exec_speed.png \
    thirdparty/json/test/reports/2016-08-29-fuzz/fuzz.tiff \
    thirdparty/json/test/reports/2016-08-29-fuzz/high_freq.png \
    thirdparty/json/test/reports/2016-08-29-fuzz/index.html \
    thirdparty/json/test/reports/2016-08-29-fuzz/low_freq.png \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/README.md \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/conformance_Nlohmann (C++11).md \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/conformance_overall_Result.png \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_1._Parse_Memory_(byte).png \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_1._Parse_Time_(ms).png \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_2._Stringify_Time_(ms).png \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_3._Prettify_Time_(ms).png \
    thirdparty/json/test/reports/2016-09-09-nativejson_benchmark/performance_Corei7-4980HQ@2.80GHz_mac64_clang7.0_7._Code_size_FileSize_(byte).png \
    thirdparty/json/test/reports/2016-10-02-fuzz/exec_speed.png \
    thirdparty/json/test/reports/2016-10-02-fuzz/fuzz.tiff \
    thirdparty/json/test/reports/2016-10-02-fuzz/high_freq.png \
    thirdparty/json/test/reports/2016-10-02-fuzz/index.html \
    thirdparty/json/test/reports/2016-10-02-fuzz/low_freq.png \
    thirdparty/json/test/thirdparty/Fuzzer/CMakeLists.txt \
    thirdparty/json/test/thirdparty/Fuzzer/FuzzerExtFunctions.def \
    thirdparty/json/test/thirdparty/Fuzzer/FuzzerFlags.def \
    thirdparty/json/test/thirdparty/Fuzzer/README.txt \
    thirdparty/json/test/thirdparty/Fuzzer/build.sh \
    thirdparty/json/test/thirdparty/Fuzzer/cxx.dict \
    thirdparty/json/test/thirdparty/Fuzzer/test/CMakeLists.txt \
    thirdparty/json/test/thirdparty/Fuzzer/test/afl-driver-extra-stats.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/afl-driver-stderr.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/caller-callee.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/coverage.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/dict1.txt \
    thirdparty/json/test/thirdparty/Fuzzer/test/dump_coverage.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-customcrossover.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-custommutator.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-dict.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-dirs.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-fdmask.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-finalstats.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-flags.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-jobs.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-leak.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-oom-with-profile.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-oom.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-printcovpcs.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-runs.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-seed.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-segv.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-singleinputs.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-threaded.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-timeout.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-traces-hooks.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer-ubsan.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/fuzzer.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/hi.txt \
    thirdparty/json/test/thirdparty/Fuzzer/test/lit.cfg \
    thirdparty/json/test/thirdparty/Fuzzer/test/lit.site.cfg.in \
    thirdparty/json/test/thirdparty/Fuzzer/test/merge.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/minimize_crash.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/no-coverage/CMakeLists.txt \
    thirdparty/json/test/thirdparty/Fuzzer/test/repeated-bytes.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/shrink.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/simple-cmp.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/standalone.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/swap-cmp.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/trace-malloc.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/ubsan/CMakeLists.txt \
    thirdparty/json/test/thirdparty/Fuzzer/test/ulimit.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/uninstrumented/CMakeLists.txt \
    thirdparty/json/test/thirdparty/Fuzzer/test/unit/lit.cfg \
    thirdparty/json/test/thirdparty/Fuzzer/test/unit/lit.site.cfg.in \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-cmp.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-cmp2.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-cmp3.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-cmp4.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-div.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-load.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-mem.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-set.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-strcmp.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-strncmp.test \
    thirdparty/json/test/thirdparty/Fuzzer/test/value-profile-switch.test \
    thirdparty/json/test/thirdparty/doctest/LICENSE.txt \
    thirdparty/json/test/thirdparty/fifo_map/LICENSE.MIT \
    thirdparty/json/test/thirdparty/imapdl/filterbr.py \
    thirdparty/json/test/thirdparty/imapdl/gpl-3.0.txt \
    thirdparty/json/third_party/amalgamate/CHANGES.md \
    thirdparty/json/third_party/amalgamate/LICENSE.md \
    thirdparty/json/third_party/amalgamate/README.md \
    thirdparty/json/third_party/amalgamate/amalgamate.py \
    thirdparty/json/third_party/amalgamate/config.json \
    thirdparty/json/third_party/cpplint/LICENSE \
    thirdparty/json/third_party/cpplint/README.rst \
    thirdparty/json/third_party/cpplint/cpplint.py \
    thirdparty/json/third_party/cpplint/update.sh \
    thirdparty/json/third_party/gdb_pretty_printer/README.md \
    thirdparty/json/third_party/gdb_pretty_printer/nlohmann-json.py \
    thirdparty/json/wsjcpp.yml
